### ISSUE TITLE
Where is Windows installation?

### ISSUE THREAD

**Issue by ow-ph** [mgp25/curve25519-php#1]
Hi @mgp25 :)

Is there a way to use end to end enc on Windows?

**Comment by mgp25** [comment]
@casion Hi, yes you need to compile this source in windows for PHP, and you will get a dll, and then add that dll to your php.ini

I don't know how to compile this in windows, thats why there is no instructions, but if someone compile it, send me dll's and ill post them so other people can just download them.

Regards
