### ISSUE TITLE
Error in make command

### ISSUE THREAD

**Issue by emontoro** [mgp25/curve25519-php#13]
Hello I'm trying compile the extension but it produce some errors, I hope you can help me

Regards

About my development environment
CentOS 6.7
64 bits
Core 2.6.32 
rhel 6
PHP 7.0.5RC1
Zend Engine v3.0.0

**Error Message:**
[root@admin curve25519-php-master]# make
/bin/sh /opt/curve25519-php-master/libtool --mode=compile cc  -I. -I/opt/curve25519-php-master -DPHP_ATOM_INC -I/opt/curve25519-php-master/include -I/opt/curve25519-php-master/main -I/opt/curve25519-php-master -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/curve25519-php-master/curve.c -o curve.lo 
libtool: compile:  cc -I. -I/opt/curve25519-php-master -DPHP_ATOM_INC -I/opt/curve25519-php-master/include -I/opt/curve25519-php-master/main -I/opt/curve25519-php-master -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/curve25519-php-master/curve.c  -fPIC -DPIC -o .libs/curve.o
/opt/curve25519-php-master/curve.c:37:40: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
/opt/curve25519-php-master/curve.c: In function ‘zif_curve25519_sign’:
/opt/curve25519-php-master/curve.c:37: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
/opt/curve25519-php-master/curve.c:37: error: (Each undeclared identifier is reported only once
/opt/curve25519-php-master/curve.c:37: error: for each function it appears in.)
/opt/curve25519-php-master/curve.c:76:33: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
/opt/curve25519-php-master/curve.c: In function ‘zif_curve25519_private’:
/opt/curve25519-php-master/curve.c:76: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
/opt/curve25519-php-master/curve.c:97:37: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
/opt/curve25519-php-master/curve.c: In function ‘zif_curve25519_public’:
/opt/curve25519-php-master/curve.c:97: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
/opt/curve25519-php-master/curve.c:124:34: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
/opt/curve25519-php-master/curve.c: In function ‘zif_curve25519_shared’:
/opt/curve25519-php-master/curve.c:124: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
make: **\* [curve.lo] Error 1

**Comment by dswtech** [comment]
same error here,

OS : Fedora 23 64bit
PHP 7.0.4 (cli) (built: Mar  2 2016 17:31:49) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

I think this cannot compile on PHP 7 ??

In PHP 5.6, my installation is succes

**Comment by mgp25** [comment]
This is only for php 5.6

**Comment by emontoro** [comment]
I would like to support the growth of this project ($). But I do not know the process that I need to follow, can you guide me?
