### ISSUE TITLE
It is supported on Raspberry PI?

### ISSUE THREAD

**Issue by jalvarezpiedra** [mgp25/curve25519-php#14]
Hello, just ask if these extensions (curve25519.so and protobuf.so) operating in the Raspberry PI, I use a Linux distribution (Raspbian), currently operating in WINDOWS achieved, but try Raspbian fails to operate.

Chat-API is great for use with WhastApp but my PC can not be on all day, so I need to run my Raspberry PI.

I use command: **php -m**
<a href="http://s1199.photobucket.com/user/jalvarezpiedra/media/img_zpsy7uqck1b.jpg.html" target="_blank"><img src="http://i1199.photobucket.com/albums/aa468/jalvarezpiedra/img_zpsy7uqck1b.jpg" border="0" alt=" photo img_zpsy7uqck1b.jpg"/></a>

**Comment by eelgaev** [comment]
You need to compile these manually since you use ARM Architecture instead of x86.
I have compiled these two libraries and they work fine on ARM.
What kind of raspberry pi do you use?

**Comment by jalvarezpiedra** [comment]
Okoyl Hi, I'm using the Raspberry Pi 2 Model B it is powered by ARM 32-bit processor, but I'll probably buy the new Raspberry Pi Model B 3 CPU ARM 64-bit Quad-Core 1.2 GHz.

I'm working on a project for my home, my idea is to use my Raspberry Pi with Chat-API to send messages using WhatsApp and these can do actions on my house, for example I can turn on and off the light in my room with only send a message Whatsapp my Raspberry Pi, also want to make my Arduino detects motion in my room and this can notify my Raspberry Pi which in turn takes a photo with IP-Camera and sends an image Whatsapp my cell phone number.

My project currently works wonders on my desktop, but I can not have my PC on every day because it consumes a lot of energy, so I need to use Chat-API on my Raspberry Pi.

**PLEASE, PLEASE, PLEASE you can compile and upload these libraries to be able to continue working on my project, I'll thank you very much for your help.**

NOTE: I added an image is built as a part of my project, I still need to finish some things.
<a href="http://s1199.photobucket.com/user/jalvarezpiedra/media/IMG_20160330_215740_zpssaeumd5j.jpg.html" target="_blank"><img src="http://i1199.photobucket.com/albums/aa468/jalvarezpiedra/IMG_20160330_215740_zpssaeumd5j.jpg" border="0" alt=" photo IMG_20160330_215740_zpssaeumd5j.jpg"/></a>

**Comment by jalvarezpiedra** [comment]
**ESPAÑOL**
Hola Okoyl, yo estoy usando la Raspberry Pi 2 Model B esta funciona con procesador ARM de 32 bits, pero yo probablemente voy a comprar el nuevo Raspberry Pi 3 Model B CPU ARM 64 bits Quad-Core 1.2 GHz.

Yo estoy trabajando en un proyecto para mi casa, mi idea es usar mi Raspberry Pi con Chat-API para yo enviar mensajes usando Whatsapp y estos pueda hacer acciones sobre mi casa, por ejemplo yo puedo encender y apagar la luz de mi cuarto con solo enviar un mensaje de Whatsapp a mi Raspberry Pi, tambien quiero hacer que mi Arduino detecte movimiento en mi cuarto y este pueda notificar a mi Raspberry Pi la cual a su vez toma una foto con la PI-Camera y envia una  imagen por Whatsapp a mi numero de celular.

Mi proyecto actualmente funciona de maravilla sobre mi PC de escritorio, pero yo no puedo tener mi PC todos los dias encendido porque consume mucha energia, por eso yo necesito usar Chat-API sobre mi Raspberry Pi.

**POR FAVOR, POR FAVOR, POR FAVOR tu puedes compilar y subir estas librerias para yo poder seguir trabajando en mi proyecto, yo te voy agradecer mucho por tu ayuda.**

NOTA: Yo agrego una imagen de como esta construido una parte de mi proyecto, todavia me falta terminar algunas cosas.
<a href="http://s1199.photobucket.com/user/jalvarezpiedra/media/IMG_20160330_215740_zpssaeumd5j.jpg.html" target="_blank"><img src="http://i1199.photobucket.com/albums/aa468/jalvarezpiedra/IMG_20160330_215740_zpssaeumd5j.jpg" border="0" alt=" photo IMG_20160330_215740_zpssaeumd5j.jpg"/></a>

**Comment by mgp25** [comment]
```
phpize
./configure
make
sudo make install
```

@jalvarezpiedra nice project

Regards
