### ISSUE TITLE
Not working in windows 10

### ISSUE THREAD

**Issue by samuelg78** [mgp25/curve25519-php#18]
Hi, the dlls are not working in windows 10. Its running fine in windows 7. Anyone have this problem? The error:

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_curve25519_ts.dll' - %1 is not a valid Win32 application.

 in Unknown on line 0

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_protobuf_ts.dll' - %1 is not a valid Win32 application.

 in Unknown on line 0

Please advice.

**Comment by mgp25** [comment]
http://lmgtfy.com/?q=PHP+Warning%3A+PHP+Startup%3A+Unable+to+load+dynamic+library+%20-+%251+is+not+a+valid+Win32+application.

Not related
