### ISSUE TITLE
Ubuntu 16.04 curve25519 installed but not decrypting

### ISSUE THREAD

**Issue by edudesouza** [mgp25/curve25519-php#19]
I am setting up a Ubuntu 16.04, in theory everything installed, curve25519, protobuf and crypto.
But for some how, curve25519 seems to be not decrypting my messages.
Is there some other environment variable that I should check?

I have a Centos running smoothly, this time I am trying another machine this time with Ubuntu.

[PHP Modules]
bcmath
bz2
calendar
Core
crypto
ctype
curl
curve25519
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by mgp25** [comment]
Not a curve issue. Open a new issue in Chat API and paste debug log.
