### ISSUE TITLE
Unable to phpize in windows

### ISSUE THREAD

**Issue by abhayprakash** [mgp25/curve25519-php#2]
This module easily got phpized in linux and gave .so, but phpizing in windows is not happening. Can you provide dll for it?

**Comment by mgp25** [comment]
I dont have windows sorry

**Comment by fabriciomurta** [comment]
Hello! I believe you can phpize on windows if you install and use cygwin! And also, of course install the php package on it.

**Comment by avengerx** [comment]
Hello! I believe you can phpize on windows if you install and use cygwin! And also, of course install the php package on it.

**Comment by kasikn77** [comment]
How to compile dll for windows
https://www.sitepoint.com/compiling-php-from-source-on-windows/

**Comment by pinfort** [comment]
I added configuration file for windows(config.w32).
Now you can do that.
