### ISSUE TITLE
install on windows 

### ISSUE THREAD

**Issue by ilhamiarie** [mgp25/curve25519-php#4]
how do I install this application on windows 7 ? thanks for the solution

**Comment by mgp25** [comment]
Sorry, i don't how how to compile extension in windows, but i suppose you will find any guide in google.

Regards

**Comment by Gielert** [comment]
I've compiled them for you guys. The zip contains both the Thread safe and non-Thread safe version. The binaries are compiled for PHP 5.6 x86.

You can download them here:
https://www.dropbox.com/s/8vlxu7ensto1q6n/curve25519-php_x86.zip?dl=0

Here is the virustotal: https://www.virustotal.com/en/file/5ced36f5b30f2fd8841bd9bc5e6cb7874e2c8f71416c50edb93daf76fecee46e/analysis/1451938278/
The SHA256 is: 5ced36f5b30f2fd8841bd9bc5e6cb7874e2c8f71416c50edb93daf76fecee46e

**Comment by mgp25** [comment]
@Gielert thats awesome, i'll add it. If you don't mind, can you compile the php protobuf extension too?
https://github.com/allegro/php-protobuf

Thanks

Regards

**Comment by Gielert** [comment]
@mgp25 Already did that :D

https://github.com/allegro/php-protobuf/issues/4

**Comment by ilhamiarie** [comment]
@Gielert thanks a lot.

**Comment by mgp25** [comment]
@Gielert Thanks, I owe you one! :smile:

**Comment by arhakim** [comment]
@Gielert I got this message when run _php -v_ in command line windows:

```
C:\xampp\php>php -v
PHP Warning:  PHP Startup: curve25519: Unable to initialize module
Module compiled with build ID=API20131226,NTS,VC11
PHP    compiled with build ID=API20131226,TS,VC11
These options need to match
 in Unknown on line 0

Warning: PHP Startup: curve25519: Unable to initialize module
Module compiled with build ID=API20131226,NTS,VC11
PHP    compiled with build ID=API20131226,TS,VC11
These options need to match
 in Unknown on line 0
PHP 5.6.12 (cli) (built: Aug  6 2015 12:06:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

Did you know how to resolve it?

Thanks

**Comment by sgatu** [comment]
@arhakim As you can see in the error, you installed the NTS version on a TS PHP, in the dropbox link, you have two dll one NTS and the other TS. You have to copy the TS version in your php folder instead of the NTS.

**Comment by yashrs** [comment]
@Gielert If you could please tell, how did you compile that ? Could you send in some sort of small tutorial or steps for the same pleaseeee ?  Because I need to compile it for x64 !

**Comment by yashrs** [comment]
@Gielert I get the following error - 

> PHP Warning:  PHP Startup: Unable to load dynamic library 'c:/wamp/bin/php/php5.4.12/ext/php_curve25519_nts.dll' - %1 is not a valid Win32 application.
>  in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library 'c:/wamp/bin/php/php5.4.12/ext/php_protobuf_nts.dll' - %1 is not a valid Win32 application.
>  in Unknown on line 0

**Comment by dswtech** [comment]
@Gielert would you mind compile it for x64 ?

**Comment by Gielert** [comment]
@dswtech Sure thing

https://www.dropbox.com/s/1j7fnkzk53wlfoa/curve25519-php_x64.zip?dl=0
The zip contains both the Thread-safe and the Non Thread-safe.

Here's the virustotal:
https://www.virustotal.com/nl/file/d5788f87e16e7a75ee06cd9d0fc1c9726058fd702b9638d603fed6df65144104/analysis/1464036132/

sha256: d5788f87e16e7a75ee06cd9d0fc1c9726058fd702b9638d603fed6df65144104

**Comment by dswtech** [comment]
Thx @Gielert  maybe @mgp25 will add to git along with protobuf x64 compiled by @Gielert which is posted here https://github.com/allegro/php-protobuf/issues/56

https://www.dropbox.com/s/lfhox1rm80xidw6/php-protobuf_x64.zip?dl=0

**Comment by Jnsa** [comment]
I have the same problem of @yashrs i already try x86 and x64, ts and nts on xampp and i get the same error in any cases. Pls Help!

**Comment by Gielert** [comment]
@Jnsa Which PHP version are you on?

**Comment by Jeffrey-Kimani** [comment]
I am running the binaries and i keep an error 
```bash
PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_protobuf_nts.dll' - The specified module could not be found.
```

But the module is already in the specified directory. I am running php 7.1.12 on windows. Please help
