### ISSUE TITLE
Call to undefined function curve25519_private()

### ISSUE THREAD

**Issue by tmcls** [mgp25/curve25519-php#7]
I have installed curve and can find it in my PHPinfo():
![PHPInfo() Curve25519](https://www.dropbox.com/s/8jlk76z9zyrz3ox/Screenshot%202015-12-30%2012.13.55.png?dl=1)

But my script give the error: 

``` bash
PHP Fatal error:  Call to undefined function curve25519_private() in Curve.php on line 14
```

Which has the following code:

``` php
<?php
/* codeline 1-12... */

   $secureRandom = self::getSecureRandom();
   $private = curve25519_private($secureRandom);
   $public = curve25519_public($private);

/* .... */
```

After more research the extension only returns the following functions

``` php
/* print_r(get_extension_funcs("curve25519")); */
Array
(
    [0] => curve25519_public
    [1] => curve25519_shared
)
```

So not the `curve25519_private()`, `curve25519_sign()` or `curve25519_verify()` functions...

How to handle this?

**Comment by Lugat** [comment]
Got the same problem on our virtual server. Any solution?

**Comment by tmcls** [comment]
There are multiple versions of Curve25519 on Github. Use this one: https://github.com/mgp25/curve25519-php

**Comment by Lugat** [comment]
Thanks :)
